#ifndef FTERMINAL_HACKING_H
#define FTERMINAL_HACKING_H

void hack(const char *password);

#define GUESSES_FOLDER "guesses"

#define HACK_HEADER "ROBCO INDUSTRIES (TM) TERMLINK PROTOCOL\n\
ENTER PASSWORD NOW"
#define HACK_HEADER_LINES 2

#define GUESS_COUNT 12

#define CHARS_IN_ROW 12
#define COL_COUNT 2

#endif //FTERMINAL_HACKING_H
